#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# Wallpaper
$HOME/.fehbg &

# Picom
picom &

# Dunst
# /usr/bin/dunst &
/usr/bin/wired &

# Polybar
$HOME/.config/polybar/launch.sh

# libinput-gestures
libinput-gestures-setup start

# Brightness
#$HOME/.scripts/brightness_control_startup.sh

# Network Manager
nm-applet &

# Show Off
# alacritty --hold -e $HOME/.scripts/show_off.sh &

# Focus and Pointer
bspc config focus_follows_pointer true

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Spotify desktop='^10'

bspc rule -a firefox:Devtools state=floating rectangle=800x500+1920+290
bspc rule -a firefox-developer-edition:Devtools state=floating rectangle=800x500+1920+290
bspc rule -a firefox:Navigator "WM_NAME=Sign In - Google Accounts — Firefox Developer Edition" state=floating 
bspc rule -a firefox-developer-edition:Navigator "WM_NAME=Sign In - Google Accounts — Firefox Developer Edition" state=floating 

# Scratchpad
bspc rule -a scratchpad sticky=on state=floating
