swipe:
  3:
    left:
      command: playerctl previous
    right:
      command: playerctl next
    up:
      update:
        command: ~/.scripts/volume_control.sh raise
        interval: 2
    down:
      update:
        command: ~/.scripts/volume_control.sh lower
        interval: 2
  4:
    left:
      update:
        command: bspc desktop -f next.occupied
        interval: 3
    right:
      update:
        command: bspc desktop -f prev.occupied
        interval: 3
    up:
      command: bspc desktop -l next
    down:
      command: ~/.scripts/scratchpad.sh
      threshold: 0.5
hold:
  3:
    command: playerctl play-pause
    threshold: 0
