require('options')

require('lazy-config')
require('ayu').colorscheme()
require('dashboard-config')
require('treesitter-config')
require('indent-config')
require('telescope-config')
require('lsp-config')
require('nvimtree-config')
require('barbecue-config')
require('bufferline-config')
require('lualine-config')
require('gitsigns').setup()
