[Obsidian]
type = drive
scope = drive
token = {"access_token":"ya29.a0AcM612yWgw2hwnl6L0fRhUBBK7RrCczP-fDQUzgbNbywMwrL0JQy99RxnKsRPJvNawXxzXExlmHxFVfftwv-n4vCvzDKrdKIrbbyK4Ger5PqxPXea1Z1HZaqWgD7oYYCpBRt1v8LlOhDaf9LCTdITmfEWEdu3m1scLscdX8TnsQaCgYKAXwSARASFQHGX2Mie_18fBkISJwqSg7te11ONg0178","token_type":"Bearer","refresh_token":"1//0gGiIGXEhhfdtCgYIARAAGBASNgF-L9Ir4XgKgHnBsZCuSD92n0v441uy1QgVmNpWhqrKZ4xEKAKBUqX4B-j91ufnA0CqwYyFQg","expiry":"2024-09-09T17:17:48.924737703+05:30"}
team_drive = 
root_folder_id = 1-2qmT2S-8LkRxjqCb2jGd2kCnwwsSBJw

