[Obsidian]
type = drive
scope = drive
token = {"access_token":"ya29.a0AcM612znhpBUSJfJN1VpC3X5UPTVskn_N4CjXOLwlUfmK-ZkPBCcH4x3l8O_jRYkGwvxSjkXLt7XjKaslvuzl4Fr9kcAxDGrFuJ8rnCQVbgvePunkmt810jMur3Xpbj95SRFxDQAC1R3OPoMpifEt038iMje6EC_GAwUaCgYKAdESARASFQHGX2MiZBBxdhQEMz2590VG4PR-gA0171","token_type":"Bearer","refresh_token":"1//0gGiIGXEhhfdtCgYIARAAGBASNgF-L9Ir4XgKgHnBsZCuSD92n0v441uy1QgVmNpWhqrKZ4xEKAKBUqX4B-j91ufnA0CqwYyFQg","expiry":"2024-08-08T20:55:27.187281458+05:30"}
team_drive = 
root_folder_id = 1-2qmT2S-8LkRxjqCb2jGd2kCnwwsSBJw

